n1 = input('Digite algo')
print('O tipo primitivo é', type(n1))
print('Só tem espaço', n1.isspace())
print('é um numero', n1.isnumeric())
print('é alfabetico?', n1.isalpha())
print('é alfanumerico', n1.isalnum())
print('esta em maiuscula', n1.isupper())
print('esta em minuscula', n1.islower())
print('esta capitalizada', n1.istitle())